# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Unofficial Google-Health-CLI for the Google Health API"
  homepage "https://github.com/rudrankriyam/Google-Health-CLI"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/v1.0.2/ghealth_1.0.2_darwin_amd64.tar.gz"
      sha256 "cf8aa3251045a7831c090f11b0d9dfd20f2e16bd564fbe146c83019e5f9793d9"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/v1.0.2/ghealth_1.0.2_darwin_arm64.tar.gz"
      sha256 "fcb006ac7e8d5bfdf2756125836b7f2561b6194bad75c332f6cbc355ec9199ab"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/v1.0.2/ghealth_1.0.2_linux_amd64.tar.gz"
      sha256 "ae792f6e16f727dedde0b690cfa5039838e659df18cbe45498abca6aea457ab8"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/v1.0.2/ghealth_1.0.2_linux_arm64.tar.gz"
      sha256 "2e4d99b052f1680579ad65d466a41867d80df26736e611c390e3a4d277c672cb"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
