# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Google Health API workbench CLI"
  homepage "https://github.com/rudrankriyam/google-health-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.1/ghealth_1.0.1_darwin_amd64.tar.gz"
      sha256 "c93351e5c3c71fdda2a8cbe0b99442b5f6b1a23f61b24b7c4887b8430f071b1a"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.1/ghealth_1.0.1_darwin_arm64.tar.gz"
      sha256 "cc446bd2a40f38653f7b42ecf19f118d29f2bc360d73103e5c8d117d64738372"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.1/ghealth_1.0.1_linux_amd64.tar.gz"
      sha256 "f119ff716ebbb51ef8267b90cd48e8db3cc59c8399e584822380660f9d70bd17"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.1/ghealth_1.0.1_linux_arm64.tar.gz"
      sha256 "63e3492aab2b3d90d9b852fffbf074f86c9a7e66ffe3547e4fafb88d7f339e92"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
