# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Google Health API workbench CLI"
  homepage "https://github.com/rudrankriyam/google-health-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.0/ghealth_1.0.0_darwin_amd64.tar.gz"
      sha256 "075ead92c536200d455564a01ce820cc5ac14d50eddccbffd6e92403546ddbf4"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.0/ghealth_1.0.0_darwin_arm64.tar.gz"
      sha256 "1d744e65c0dd4ae5fde09a48459efe907e902d45a2fc38a8929b00c686d9f7a1"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.0/ghealth_1.0.0_linux_amd64.tar.gz"
      sha256 "8be12fe1a37a50845669e4d4879c97fbea63fd2ed71e86c3c26beec504bccee1"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/google-health-cli/releases/download/v1.0.0/ghealth_1.0.0_linux_arm64.tar.gz"
      sha256 "eb5b74bab192bd88789793b889bcc8bd5f7019022a75d9f5bb44f25a23291f8b"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
